class ConstLanguage():
    """class for storing all const Language"""
    MENU_RIG = 10
    MENU_RIG_NEW = 11
    MENU_RIG_REFRESH = 12 
    MENU_RIG_RENAME = 13
    MENU_RIG_DELETE_CURRENT = 14 
    MENU_RIG_DELETE_ALL =  15
    MENU_RIG_CHANGE_FOLDER = 16

    MENU_RIG_OPTIONS = 20
    MENU_RIG_OPTIONS_IMPORT = 21 
    MENU_RIG_OPTIONS_IMPORT_ACTIVE = 21 
    MENU_RIG_OPTIONS_IMPORT_ZIP = 22

    MENU_RIG_OPTIONS_EXPORT = 23
    MENU_RIG_OPTIONS_EXPORT_ACTIVE = 24
    MENU_RIG_OPTIONS_EXPORT_ZIP = 25

    MENU_HELP = 50
    MENU_HELP_CHECK_UPDATE = 51
    MENU_HELP_ONLINE_HELP = 52
    MENU_HELP_ABOUT = 53